version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./peppermint/db:/data/db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint
    ports:
      - 5432:5432

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    restart: always
    volumes:
      - ./peppermint/db:/data/db
    user: root
    expose:
      - 8025
    ports:
      - 8025:8025
      - 1025:1025
    healthcheck:
      test: echo | telnet 127.0.0.1 1025

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: peppermint
      MINIO_ROOT_PASSWORD: peppermint#Strong#Password
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}
    
